# Generated by Django 3.2.4 on 2022-04-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('nombre3', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('apellido3', models.CharField(max_length=50, null=True)),
                ('fechanacimiento', models.DateField()),
                ('foto', models.CharField(max_length=500, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('cui', models.CharField(max_length=13, null=True)),
                ('codigo', models.CharField(max_length=13)),
                ('telefono1', models.PositiveIntegerField(null=True)),
                ('telefono2', models.PositiveIntegerField(null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('estado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('sexo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('nombre3', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('apellido3', models.CharField(max_length=50, null=True)),
                ('fechanacimiento', models.DateField()),
                ('foto', models.CharField(max_length=500, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('cui', models.CharField(max_length=13, null=True)),
                ('codigo', models.CharField(max_length=13)),
                ('telefono1', models.PositiveIntegerField(null=True)),
                ('telefono2', models.PositiveIntegerField(null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('estado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('sexo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('inscripcion', models.FloatField()),
                ('mensualidad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre1', models.CharField(max_length=50)),
                ('nombre2', models.CharField(max_length=50, null=True)),
                ('nombre3', models.CharField(max_length=50, null=True)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50, null=True)),
                ('apellido3', models.CharField(max_length=50, null=True)),
                ('fechanacimiento', models.DateField()),
                ('foto', models.CharField(max_length=500, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('cui', models.CharField(max_length=13, null=True)),
                ('carnet', models.CharField(max_length=13)),
                ('telefono1', models.PositiveIntegerField(null=True)),
                ('telefono2', models.PositiveIntegerField(null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('estado', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estado')),
                ('sexo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sexo')),
            ],
        ),
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipousuario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=256)),
                ('administrativo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.administrativo')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiante')),
                ('requisito', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requisito')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoCatedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('catedratico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catedratico')),
                ('requisito', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.requisito')),
            ],
        ),
        migrations.AddField(
            model_name='requisito',
            name='tipousuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.tipousuario'),
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('apellido', models.CharField(max_length=300)),
                ('telefono', models.PositiveIntegerField()),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('cupo', models.PositiveIntegerField()),
                ('activo', models.BooleanField()),
                ('seccion', models.CharField(max_length=2)),
                ('catedratico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catedratico')),
                ('ciclo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.ciclo')),
                ('curso', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.curso')),
            ],
        ),
        migrations.CreateModel(
            name='ClaseDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveIntegerField(default=0)),
                ('estudiante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.estudiante')),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.claseheader')),
            ],
        ),
    ]
